"""correct job table

Revision ID: 760729ef071f
Revises: 104945a2537a
Create Date: 2024-05-16 13:24:11.557179

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '760729ef071f'
down_revision: str | None = '104945a2537a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customerfrequencylink')
    op.drop_table('customerjobslink')
    op.add_column('customer', sa.Column('frequencyId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'customer', 'frequency', ['frequencyId'], ['frequencyId'])
    op.add_column('job', sa.Column('customerId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'job', 'customer', ['customerId'], ['customerId'])
    op.drop_constraint('servicelink_invoiceId_fkey', 'servicelink', type_='foreignkey')
    op.drop_constraint('servicelink_customerId_fkey', 'servicelink', type_='foreignkey')
    op.drop_column('servicelink', 'customerId')
    op.drop_column('servicelink', 'invoiceId')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicelink', sa.Column('invoiceId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('servicelink', sa.Column('customerId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('servicelink_customerId_fkey', 'servicelink', 'customer', ['customerId'], ['customerId'])
    op.create_foreign_key('servicelink_invoiceId_fkey', 'servicelink', 'invoice', ['invoiceId'], ['invoiceId'])
    op.drop_constraint(None, 'job', type_='foreignkey')
    op.drop_column('job', 'customerId')
    op.drop_constraint(None, 'customer', type_='foreignkey')
    op.drop_column('customer', 'frequencyId')
    op.create_table('customerjobslink',
    sa.Column('customerId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('jobId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['customerId'], ['customer.customerId'], name='customerjobslink_customerId_fkey'),
    sa.ForeignKeyConstraint(['jobId'], ['job.jobId'], name='customerjobslink_jobId_fkey'),
    sa.PrimaryKeyConstraint('customerId', 'jobId', name='customerjobslink_pkey')
    )
    op.create_table('customerfrequencylink',
    sa.Column('frequencyId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('customerId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['customerId'], ['customer.customerId'], name='customerfrequencylink_customerId_fkey'),
    sa.ForeignKeyConstraint(['frequencyId'], ['frequency.frequencyId'], name='customerfrequencylink_frequencyId_fkey'),
    sa.PrimaryKeyConstraint('frequencyId', 'customerId', name='customerfrequencylink_pkey')
    )
    # ### end Alembic commands ###
