"""adjusted None

Revision ID: a975f6884409
Revises: 0cc8162897ec
Create Date: 2024-05-14 11:51:59.748515

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a975f6884409'
down_revision: str | None = '0cc8162897ec'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('frequency', 'customerId',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('frequency', 'customerId',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
